import { SbomDocument, ExtractMetadataResult } from '../gen/messages_pb';
import { AxiomContext } from '../gen/axiomContext';
import { parseSbom } from './lib/parse';
import { metadataToMsg } from './lib/mappers';

/**
 * Extract document-level metadata verbatim: the tool that created it, its
 * creation timestamp exactly as declared in the document (never generated by
 * this node), the primary/described component, and the document's own
 * name/namespace/serial number.
 *
 * @param ax - Platform context: ax.log for logging, ax.secrets for secrets.
 */
export function extractMetadata(ax: AxiomContext, input: SbomDocument): ExtractMetadataResult {
  const parsed = parseSbom(input.getText(), input.getFormatHint());
  const out = new ExtractMetadataResult();
  out.setOk(parsed.ok);
  out.setError(parsed.error);
  if (parsed.ok) {
    out.setMetadata(metadataToMsg(parsed.metadata));
  }
  return out;
}
